---
title: "Generative Art Assignment"
author: "Emily Cunningham"
date: 06-04-2024
format: html
editor: visual
    toc: true # includes a table of contents in rendered html format
execute: # for all code chunks
    warning: false # do not display warnings
    message: false # do not display messages
---

Link to repo: <https://github.com/environmentalemily/Generative-Art-.git>

Part 2a: Workshop \[structured\]

a\.

```{r}
#load in packages
library(ggplot2)
library(tibble)

#load in data
mpg 

```

b.  doing the excersizes

```{r}
mpg %>% 
  ggplot(aes(displ, hwy, colour = drv)) + 
  geom_jitter(show.legend = FALSE, size = 3, height = 1000, colour = "#C2A43C") + #make data points mustard yellow
  geom_jitter(show.legend = FALSE, size = 1, colour = "#AE123A", height = 10) + #set height of points to create a ring
  
  coord_polar() + #creates a coordinate plot 
  theme_void() + 
  scale_color_brewer()
```
```{r}


polar_art <- function(seed, n, palette) {
  
  # set the state of the random number generator
  set.seed(seed)
  
  # data frame containing random values for 
  # aesthetics we might want to use in the art
  dat <- tibble(
    x0 = runif(n),
    y0 = runif(n),
    x1 = x0 + runif(n, min = -.2, max = .2),
    y1 = y0 + runif(n, min = -.2, max = .2),
    shade = runif(n), 
    size = runif(n)
  )
  
  # plot segments in various colours, using 
  # polar coordinates and a gradient palette
  dat |> 
    ggplot(aes(
      x = x0,
      y = y0,
      xend = x1,
      yend = y1,
      colour = shade,
      size = size
    )) +
    geom_segment(show.legend = FALSE) +
    coord_polar() +
    scale_y_continuous(expand = c(0, 0)) +
    scale_x_continuous(expand = c(0, 0)) + 
    scale_colour_gradientn(colours = palette) + 
    scale_size(range = c(0, 10)) + 
    theme_void()
}

polar_art(
  seed = 5, 
  n = 60, 
  palette = c("#004949", "#005000", "#007A99")
)



```
```{r}
polar_art_02.R <- function(seed, n, palette) {
  
  # set the state of the random number generator
  set.seed(seed)
  
  # data frame containing random values for 
  # aesthetics we might want to use in the art
  dat <- tibble(
    x0 = runif(n),
    y0 = runif(n),
    x1 = x0 + runif(n, min = -.4, max = .4),
    y1 = y0 + runif(n, min = -.4, max = .4),
    shade = runif(n), 
    size = runif(n)
  )
  
  # plot segments in various colours, using 
  # polar coordinates and a gradient palette
  dat |> 
    ggplot(aes(
      x = x0,
      y = y0,
      xend = x1,
      yend = y1,
      colour = shade,
      size = size
    )) +
    geom_segment(show.legend = FALSE) +
    coord_polar() +
    scale_y_continuous(expand = c(0, 0)) +
    scale_x_continuous(expand = c(0, 0)) + 
    scale_colour_gradientn(colours = palette) + 
    scale_size(range = c(0, 50)) + 
    theme_void()
}

polar_art(
  seed = 5, 
  n = 1000, 
  palette = c("#AC6A9F", "#F3A469", "#D04544")
) 

```

